// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitStatsFilter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidBranchFilterPackageString = "5d00e368-00a1-4c6c-8165-837abba71fb3";
        public static Guid guidBranchFilterPackage = new Guid(guidBranchFilterPackageString);

        public const string guidFileFilterCommandString = "5448d968-2036-4a64-8f30-d2cb9f61d759";
        public static Guid guidFileFilterCommand = new Guid(guidFileFilterCommandString);

        public const string guidImagesString = "30dabb9d-dc22-412f-b7cd-4f4b77a93021";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ApplyFilterCommandID = 0x0100;
        public const int SelectBaseBranchCommandId = 0x0101;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
    }
}